__name__ = "inventory-management-system"
__version__ = "1.0"
__url__ = "https://github.com/praveen4g0/inventory-management-system"
__author__ = "Praveen"
__email__ = "praveen.thangadancha@gmail.com"
__description__ = "Basic Inventory Management System powered by Flask"
__license__ = "MIT"
